import pandas as pd
import joblib
import argparse
import sys
from pathlib import Path

# Add project root to sys.path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.utils import PATHS
from src.pipelines.feature_eng import preprocess_new_data, build_preprocessed_dataset, FEATURES

def main():
    parser = argparse.ArgumentParser(description="Predict clusters for new data.")
    parser.add_argument("--input", type=str, required=True, help="Path to raw CSV")
    parser.add_argument("--model", type=str, default="kmeans", choices=["kmeans", "gmm", "dbscan"])
    parser.add_argument("--output", type=str, default="data/processed/predictions.csv")
    args = parser.parse_args()

    # 1. Load Data
    df_raw = pd.read_csv(args.input)
    
    # 2. Get training context (to match encoder/scaler logic)
    _, _, encoder, scaler = build_preprocessed_dataset(args.input)
    
    # 3. Preprocess and Filter
    X_processed = preprocess_new_data(df_raw, encoder, scaler)
    X_final = X_processed[FEATURES]
    
    # 4. Load Model
    model_filenames = {
        "kmeans": "kmeans_customer_segmentation.pkl",
        "gmm": "gmm_customer_segmentation.pkl",
        "dbscan": "dbscan_outlier_detection.pkl"
    }
    
    model_path = PATHS["models"] / model_filenames[args.model]
    pipeline = joblib.load(model_path)
    
    # 5. Execute Prediction
    # We extract the specific model step from the pipeline
    if args.model == "kmeans":
        model = pipeline.named_steps["kmeans"]
        predictions = model.predict(X_final)
    elif args.model == "gmm":
        model = pipeline.named_steps["gaussianmixture"]
        predictions = model.predict(X_final)
    elif args.model == "dbscan":
        # DBSCAN clusters are generated by fitting to the current data
        predictions = pipeline.fit_predict(X_final)
    
    # 6. Save Results
    df_raw[f"{args.model}_cluster"] = predictions
    df_raw.to_csv(args.output, index=False)
    
    print(f"Success! Predicted {args.model.upper()} clusters for {len(df_raw)} customers.")
    print(f"Results saved to: {args.output}")

if __name__ == "__main__":
    main()